import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';
import Typed from 'react-typed';

const Navbar = () => <header id="header">
  <nav className="navbar navbar-expand-lg navbar-light w-100 border-3 border-bottom border-dark">
  <a className="navbar-brand logoNavBar p-4" href="#">
    <img src='/logo.png' id="logo" />
  </a>
  <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" 
  aria-label="Toggle navigation">
    <span className="navbar-toggler-icon"></span>
  </button>
    <div className="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul className="navbar-nav ">
        <li className="nav-item">
          <Link href="#Nosotros">
            <a className="nav-link text-dark">Nosotros</a>
          </Link>
        </li>
        <li className="nav-item">
          <Link href="#Soporte">
            <a className="nav-link text-dark">Soporte T.I</a>
          </Link>
        </li>
        <li className="nav-item">
          <Link href="#Desarrollo">
            <a className="nav-link text-dark">Desarrollo</a>
          </Link>
        </li>
        <li className="nav-item">
          <Link href="#Servicios">
            <a className="nav-link text-dark">Servicios en la Nube</a>
          </Link>
        </li>
        <li className="nav-item">
          <Link href="#Staff">
            <a className="nav-link text-dark">Staff Augmentation</a>
          </Link>
        </li>
        <li className="nav-item">
          <Link href="#Contactanos">
            <a className="nav-link text-dark">Contactanos</a>
          </Link>
        </li>
      </ul>
    </div>
  </nav>
</header>


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div id="Nosotros" className='border-3 border-bottom border-warning' style={{'height':'120vh'}}>
        <div className='Content'>
            <video autoPlay muted loop>         
              <source src="/background.mp4" type="video/mp4"/>       
            </video>
            <div className='NosotrosContent'>
              <div className='NosotrosParrafo'>
                <h1>Nosotros</h1>
                <br />
                <Typed
                    strings={[`Desde 2006, Dimensionamos, Implementamos y Administramos las soluciones tecnológicas que tu empresa necesita.
                    <br/>
                    <br/>
                    Somos tu socio tecnológico, basamos nuestros servicios en la confianza, la buena comunicación y la agilidad para brindarte soluciones flexibles, seguras y de alto 
                    impacto que te ayuden a lograr tus objetivos.`]}
                    typeSpeed={32}
                />
              </div>
              <div id="NostrosTextBackground">
               > NUEVAS 
                <ul>
                  <li>NECESIDADES</li>
                  <li>TECNOLOGÍAS</li>
                  <li>SOLUCIONES</li>
                </ul>
              </div>
            </div>
        </div>
      </div>

      <div id="Soporte" className='backgroundBlocked' style={{'height':'100vh'}}>        
          <div className='col50 Content' style={{'width':'50%', 'height' : '100%'}}>
            <video autoPlay muted loop>         
                <source src="/it.mp4" type="video/mp4"/>       
            </video>
            <div className='SoporteContent'>
                <div className='SoporteParrafo'>
                    <div className='SoporteCambia'>
                    <ul style={{'margin-right':'11px'}}>
                        <li>Concentrate </li>
                        <li>nosotros </li>
                      </ul>
                        en_tu 
                      <ul>
                        <li>negocio</li>
                        <li>tecnología</li>
                      </ul>
                    </div>
                </div>
              </div>
          </div>
          <div className='col50'>
            <div style={{'margin-top' : '69px'}}>
              <h1>Soporte T.I.</h1>
    Te apoyamos en la administración de tu infraestructura de tecnología. Contarás con un departamento de informática independiente de tu estructura o tamaño. Apoyado con personal técnico capacitado y comprometido para que todo funcione correctamente.
    Te ofrecemos asesoría en tecnología para asegurarte que tu empresa estará actualizada y aplicando las mejores herramientas y soluciones para tu negocio.
    Contamos con amplia experiencia en Administracion de Centros de Computos, Administración de Comunicaciones, Servidores, Telefonia IP y Servicio a Usuarios.
            </div>
          </div>
      </div>
      <div id="Desarrollo"  className='backgroundBlocked' style={{'height':'120vh'}}>
        <h1>Desarrollo</h1>
      </div>
      <div id="Servicios"  className='backgroundBlocked' style={{'height':'120vh'}}>
        <h1>Servicios en la Nube</h1>
      </div>
      <div id="Staff" className='backgroundBlocked' style={{'height':'120vh'}}>
        <h1>Staff Augmentation</h1>
      </div>
      <div id="Contactanos" style={{'height':'800px'}}>
        <h1>Contactanos</h1>
      </div>
    </div>
  )
}


